// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpeddfxeptxwnliuycrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwZWRkZnhlcHR4d25saXV5Y3J3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMjc1NDcsImV4cCI6MjA2NzgwMzU0N30.kGi3YzpiUWZb3dVNPCRVwHOA95SYe6sKKIV2QMaojCM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});